@startuml
'https://plantuml.com/class-diagram

Class ToDoLists{
+load initial scene
}

Class ToDoListsController{
--Methods--
+Initialize()
+editedDescription()
+clickedNewItem()
+clickedDeleteItem()
+clickedSaveList()
+clickedLoadList()
+clickedFilterComp()
+clickedFilterIncomp()
+clickedFilterAll()
+clickedClearList()
+editDescriptionEnd()
+activatedDatePicker()
}

Class ListHandler{
--Parameters--
List<ToDoList>
--Methods--
+clearList()
+saveList()
+loadList()
}

Class ToDoList{
--Parameters--
String
List<ToDoItem>
--Methods--
+createItem()
+removeItem()
+getItems()
+filterItems()
+validateDesc()
}

Class ToDoItem{
--Parameters--
String description
String dueDate
boolean completeness
--methods--
+setItemDesc()
+setItemDueDate()
+setItemCompleteness()
+getItemDesc()
+getItemDueDate()
+getItemCompleteness()
}

Class CheckBoxTableCellFactory{
..Overrides..
CheckBoxTableCell -> TableCell
}


ToDoLists ..|> ToDoListsController
ToDoLists -- ListHandler
ListHandler o- ToDoList
ToDoList o- ToDoItem
ToDoListsFXML <|- CheckBoxTableCellFactory
ToDoListsFXML o- ToDoListsController

@enduml