@startuml
'https://plantuml.com/class-diagram

Class InventoryLists{
+load initial scene
}

Class InventoryListsController{
--Methods--
+Initialize()
+clickedNewItem()
+clickedDeleteItem()
+clickedSaveListAsJSON()
+clickedLoadListAsJSON()
+clickedSaveListAsTSV()
+clickedLoadListAsTSV()
+clickedSaveListAsHTML()
+clickedLoadListAsHTML()
+clickedClearList()
+editedName()
+editNameEnd()
+editedPrice()
+editPriceEnd()
+editedSerialNum()
+editSerialNumEnd()
+clickedSearchByName()
+clickedSearchBySerialNum()
+clickedHelp()
}

Class ListHandler{
--Parameters--
List<InventoryList>
}

Class InventoryList{
--Parameters--
String
List<InventoryItem>
--Methods--
+addItem()
+removeItem()
+getItems()
+validateName()
+validatePrice()
+validateSerialNum()
+checkForSerialNumDupe()
}

Class InventoryItem{
--Parameters--
String name
String price
String serialNum
--methods--
+setItemName()
+setItemPrice()
+setItemSerialNum()
+getItemName()
+getItemPrice()
+getItemSerialNum()
}

Class ListSaveAndLoadHandler{
--methods--
+SaveListAsJSON()
+loadListAsJSON()
+SaveListAsTSV()
+loadListAsTSV()
+SaveListAsHTML()
+loadListAsHTML()
}

Class ItemSearchHandler{
--methods--
+getSearchedItems()
+searchItems()
}

InventoryLists ..|> InventoryListsController
InventoryListsController -- ListHandler
ListHandler o- InventoryList
InventoryList o- InventoryItem
InventoryListsFXML --|> InventoryListsController
ItemSearchHandler -- InventoryList
ListSaveAndLoadHandler -- InventoryList
InventoryListsController -- ItemSearchHandler
InventoryListsController -- ListSaveAndLoadHandler

@enduml